#!/bin/bash
echo "ヘルプを表示中..."
echo ""
echo ""

echo "📚 Claude Code PM - プロジェクト管理システム"
echo "============================================="
echo ""
echo "🎯 基本手順"
echo "  1. /pm:prd-new <name>        - PRD の新規作成"
echo "  2. /pm:prd-parse <name>      - PRD の Epic 化"
echo "  3. /pm:epic-decompose <name> - Task へ分解"
echo "  4. /pm:epic-sync <name>      - GitHub へ反映"
echo "  5. /pm:epic-start <name>     - 並列実行の開始"
echo ""
echo "📄 PRD コマンド"
echo "  /pm:prd-new <name>     - 新規製品要件のブレインストーミング開始"
echo "  /pm:prd-parse <name>   - PRD の実装 Epic への変換"
echo "  /pm:prd-list           - 全 PRD の一覧"
echo "  /pm:prd-edit <name>    - 既存 PRD の編集"
echo "  /pm:prd-status         - PRD の実装状況の表示"
echo ""
echo "📚 Epic コマンド"
echo "  /pm:epic-decompose <name> - Epic の Task ファイルへの分解"
echo "  /pm:epic-sync <name>      - Epic と Task の GitHub への反映"
echo "  /pm:epic-oneshot <name>   - 分解と Sync の一括実行"
echo "  /pm:epic-list             - 全 Epic の一覧"
echo "  /pm:epic-show <name>      - Epic とその Task の表示"
echo "  /pm:epic-status [name]    - Epic の進捗表示"
echo "  /pm:epic-close <name>     - Epic の完了設定"
echo "  /pm:epic-edit <name>      - Epic 詳細の編集"
echo "  /pm:epic-refresh <name>   - Task に基づく Epic 進捗の更新"
echo "  /pm:epic-start <name>     - 並列エージェント実行の開始"
echo ""
echo "📝 Issue コマンド"
echo "  /pm:issue-show <num>      - Issue と sub-issue の表示"
echo "  /pm:issue-status <num>    - Issue 状況の確認"
echo "  /pm:issue-start <num>     - 専用エージェントによる作業開始"
echo "  /pm:issue-sync <num>      - 更新の GitHub への反映"
echo "  /pm:issue-close <num>     - Issue の完了設定"
echo "  /pm:issue-reopen <num>    - close 済み Issue の再開"
echo "  /pm:issue-edit <num>      - Issue 詳細の編集"
echo "  /pm:issue-analyze <num>   - 並列 Stream の分析"
echo ""
echo "🔄 作業管理コマンド"
echo "  /pm:next               - 次の優先 Task の表示"
echo "  /pm:status             - プロジェクト全体の概況"
echo "  /pm:standup            - 日次 Standup Report"
echo "  /pm:blocked            - 阻害中の Task の表示"
echo "  /pm:in-progress        - 進行中の作業の一覧"
echo ""
echo "🔗 Sync コマンド"
echo "  /pm:sync               - GitHub との完全な双方向 Sync"
echo "  /pm:import <issue>     - 既存 GitHub Issue の取込"
echo ""
echo "🔧 保守コマンド"
echo "  /pm:validate           - システム整合性の確認"
echo "  /pm:clean              - 完了作業の archive"
echo "  /pm:search <query>     - 全内容の横断検索"
echo ""
echo "⚙️  初期設定コマンド"
echo "  /pm:init               - 依存ツールの導入と GitHub の設定"
echo "  /pm:help               - 本ヘルプの表示"
echo ""
echo "💡 要点"
echo "  • 着手可能な作業の確認: /pm:next"
echo "  • 概況の確認: /pm:status"
echo "  • Epic の手順: prd-new → prd-parse → epic-decompose → epic-sync"
echo "  • 詳細文書: README.md"

exit 0
